name: CD Pipeline - Monorepo Deployment

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  AZURE_WEBAPP_NAME_BACKEND: "my-social-scribe-backend"
  AZURE_WEBAPP_NAME_FRONTEND: "my-social-scribe-frontend"
  RESOURCE_GROUP: "conversation"

jobs:
  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      backend_changed: ${{ steps.filter.outputs.backend }}
      frontend_changed: ${{ steps.filter.outputs.frontend }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect changes in directories
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'

  deploy-backend:
    name: Deploy Backend
    needs: detect-changes
    if: needs.detect-changes.outputs.backend_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/backend:latest ./backend
          docker push ${{ env.DOCKERHUB_USERNAME }}/backend:latest

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Update Azure Web App configuration
        run: |
          az webapp config container set \
            --name ${{ env.AZURE_WEBAPP_NAME_BACKEND }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --docker-custom-image-name ${{ env.DOCKERHUB_USERNAME }}/backend:latest \
            --docker-registry-server-url https://index.docker.io/v1

          az webapp config appsettings set \
            --name ${{ env.AZURE_WEBAPP_NAME_BACKEND }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --settings DEPLOY_TIMESTAMP=$(date +%s)

  deploy-frontend:
    name: Deploy Frontend
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push frontend image
        run: |
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/frontend:latest ./frontend
          docker push ${{ env.DOCKERHUB_USERNAME }}/frontend:latest

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Update Azure Web App configuration
        run: |
          az webapp config container set \
            --name ${{ env.AZURE_WEBAPP_NAME_FRONTEND }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --docker-custom-image-name ${{ env.DOCKERHUB_USERNAME }}/frontend:latest \
            --docker-registry-server-url https://index.docker.io/v1

          az webapp config appsettings set \
            --name ${{ env.AZURE_WEBAPP_NAME_FRONTEND }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --settings DEPLOY_TIMESTAMP=$(date +%s)