name: "CI Workflow with CodeQL, Docker Build, and Formatting Check"

on:
  pull_request:
    branches:
      - "main"

jobs:
  lint-and-analyze:
    name: "Run tests, build, and CodeQL analysis with formatting check"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Set up Go"
        uses: actions/setup-go@v3
        with:
          go-version: "1.23.3"

      - name: "Check Go formatting"
        run: |
          unformatted=$(gofmt -l .)
          if [ -n "$unformatted" ]; then
            echo "The following files are not properly formatted:"
            echo "$unformatted"
            exit 1
          else
            echo "All files are properly formatted."
          fi

      - name: "Run tests"
        run: |
          export TEST_ENV=true
          cd backend
          go test ./...

      - name: "Build project"
        run: |
          cd backend
          go build ./cmd/main.go

      - name: "Set up CodeQL"
        uses: github/codeql-action/init@v2
        with:
          languages: go

      - name: "Create CodeQL database"
        run: |
          cd backend
          codeql database create codeql-db --language=go --source-root=.

      - name: "Run CodeQL analysis"
        run: |
          cd backend
          codeql analyze codeql-db \
            --format=sarif-latest \
            --output=results.sarif

      - name: "Upload SARIF results"
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: backend/results.sarif

      - name: "Check Prettier formatting in frontend"
        run: |
          cd frontend
          npx prettier --check .

  docker-build-test:
    name: "Test Docker Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Install Docker Compose"
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: "Build Docker Image"
        run: |
          cd backend
          docker-compose build
